"""Haciendo columna de pre tarea nulleable en tickets

Revision ID: 00948221ca8e
Revises: b75a5e68034a
Create Date: 2023-10-06 20:31:21.092444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00948221ca8e'
down_revision = 'b75a5e68034a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', 'descripcion',
               existing_type=mysql.MEDIUMTEXT(),
               nullable=True)
    op.alter_column('ticket', 'pre_tarea',
               existing_type=mysql.ENUM('TAREA1', 'TAREA2', 'TAREA3'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', 'pre_tarea',
               existing_type=mysql.ENUM('TAREA1', 'TAREA2', 'TAREA3'),
               nullable=False)
    op.alter_column('ticket', 'descripcion',
               existing_type=mysql.MEDIUMTEXT(),
               nullable=False)
    # ### end Alembic commands ###
