"""pequeño fix en estado de tickets

Revision ID: 4dc0c8626368
Revises: f51903454e2a
Create Date: 2023-08-26 00:31:51.846755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc0c8626368'
down_revision = 'f51903454e2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ticket_ibfk_3', 'ticket', type_='foreignkey')
    op.drop_constraint('ticket_ibfk_2', 'ticket', type_='foreignkey')
    op.drop_constraint('ticket_ibfk_1', 'ticket', type_='foreignkey')
    op.create_foreign_key(None, 'ticket', 'area', ['area_solicitante'], ['id'], source_schema='tickets', referent_schema='tickets')
    op.create_foreign_key(None, 'ticket', 'area', ['area_asignada_id'], ['id'], source_schema='tickets', referent_schema='tickets')
    op.create_foreign_key(None, 'ticket', 'usuario', ['tecnico_asignado_id'], ['id'], source_schema='tickets', referent_schema='tickets')
    op.drop_constraint('ticket_historial_ibfk_5', 'ticket_historial', type_='foreignkey')
    op.drop_constraint('ticket_historial_ibfk_1', 'ticket_historial', type_='foreignkey')
    op.drop_constraint('ticket_historial_ibfk_3', 'ticket_historial', type_='foreignkey')
    op.drop_constraint('ticket_historial_ibfk_2', 'ticket_historial', type_='foreignkey')
    op.drop_constraint('ticket_historial_ibfk_4', 'ticket_historial', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_historial', 'usuario', ['tecnico_anterior_id'], ['id'], source_schema='tickets', referent_schema='tickets')
    op.create_foreign_key(None, 'ticket_historial', 'ticket_historial', ['registro_anterior_id'], ['id'], source_schema='tickets', referent_schema='tickets')
    op.create_foreign_key(None, 'ticket_historial', 'area', ['area_anterior_id'], ['id'], source_schema='tickets', referent_schema='tickets')
    op.create_foreign_key(None, 'ticket_historial', 'usuario', ['creado_por_id'], ['id'], source_schema='tickets', referent_schema='tickets')
    op.create_foreign_key(None, 'ticket_historial', 'ticket', ['ticket_id'], ['id'], source_schema='tickets', referent_schema='tickets')
    op.drop_constraint('ticket_tarea_relacion_ibfk_3', 'ticket_tarea_relacion', type_='foreignkey')
    op.drop_constraint('ticket_tarea_relacion_ibfk_1', 'ticket_tarea_relacion', type_='foreignkey')
    op.drop_constraint('ticket_tarea_relacion_ibfk_2', 'ticket_tarea_relacion', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_tarea_relacion', 'ticket', ['ticket_id'], ['id'], source_schema='tickets', referent_schema='tickets')
    op.create_foreign_key(None, 'ticket_tarea_relacion', 'usuario', ['tecnico_id'], ['id'], source_schema='tickets', referent_schema='tickets')
    op.create_foreign_key(None, 'ticket_tarea_relacion', 'area', ['area_id'], ['id'], source_schema='tickets', referent_schema='tickets')
    op.drop_constraint('usuario_ibfk_1', 'usuario', type_='foreignkey')
    op.create_foreign_key(None, 'usuario', 'area', ['area_id'], ['id'], source_schema='tickets', referent_schema='tickets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', schema='tickets', type_='foreignkey')
    op.create_foreign_key('usuario_ibfk_1', 'usuario', 'area', ['area_id'], ['id'])
    op.drop_constraint(None, 'ticket_tarea_relacion', schema='tickets', type_='foreignkey')
    op.drop_constraint(None, 'ticket_tarea_relacion', schema='tickets', type_='foreignkey')
    op.drop_constraint(None, 'ticket_tarea_relacion', schema='tickets', type_='foreignkey')
    op.create_foreign_key('ticket_tarea_relacion_ibfk_2', 'ticket_tarea_relacion', 'usuario', ['tecnico_id'], ['id'])
    op.create_foreign_key('ticket_tarea_relacion_ibfk_1', 'ticket_tarea_relacion', 'ticket', ['ticket_id'], ['id'])
    op.create_foreign_key('ticket_tarea_relacion_ibfk_3', 'ticket_tarea_relacion', 'area', ['area_id'], ['id'])
    op.drop_constraint(None, 'ticket_historial', schema='tickets', type_='foreignkey')
    op.drop_constraint(None, 'ticket_historial', schema='tickets', type_='foreignkey')
    op.drop_constraint(None, 'ticket_historial', schema='tickets', type_='foreignkey')
    op.drop_constraint(None, 'ticket_historial', schema='tickets', type_='foreignkey')
    op.drop_constraint(None, 'ticket_historial', schema='tickets', type_='foreignkey')
    op.create_foreign_key('ticket_historial_ibfk_4', 'ticket_historial', 'usuario', ['creado_por_id'], ['id'])
    op.create_foreign_key('ticket_historial_ibfk_2', 'ticket_historial', 'usuario', ['tecnico_anterior_id'], ['id'])
    op.create_foreign_key('ticket_historial_ibfk_3', 'ticket_historial', 'ticket', ['ticket_id'], ['id'])
    op.create_foreign_key('ticket_historial_ibfk_1', 'ticket_historial', 'area', ['area_anterior_id'], ['id'])
    op.create_foreign_key('ticket_historial_ibfk_5', 'ticket_historial', 'ticket_historial', ['registro_anterior_id'], ['id'])
    op.drop_constraint(None, 'ticket', schema='tickets', type_='foreignkey')
    op.drop_constraint(None, 'ticket', schema='tickets', type_='foreignkey')
    op.drop_constraint(None, 'ticket', schema='tickets', type_='foreignkey')
    op.create_foreign_key('ticket_ibfk_1', 'ticket', 'area', ['area_asignada_id'], ['id'])
    op.create_foreign_key('ticket_ibfk_2', 'ticket', 'usuario', ['tecnico_asignado_id'], ['id'])
    op.create_foreign_key('ticket_ibfk_3', 'ticket', 'area', ['area_solicitante'], ['id'])
    # ### end Alembic commands ###
