"""Initial migration

Revision ID: 76de094b9ae8
Revises: 
Create Date: 2023-08-09 23:36:14.127436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76de094b9ae8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Enum('COMPUTOS', 'SOPORTE_TECNICO', 'TELEFONIA', 'CID', 'GDE', name='nombrearea'), nullable=False),
    sa.Column('referencia', sa.String(length=256), nullable=False),
    sa.Column('numero_gde', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tickets'
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=256), nullable=False),
    sa.Column('apellido', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('telefono', sa.String(length=256), nullable=False),
    sa.Column('perfil', sa.Enum('SOLICITANTE', 'RESPONSABLE_DE_AREA', 'COLABORADOR', 'OPERADOR', name='perfilusuario'), nullable=False),
    sa.Column('rol', sa.Enum('ADMINISTRADOR', 'EDITOR', 'LECTOR', name='rolusuario'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tickets'
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('prioridad', sa.Enum('ALTA', 'MEDIA', 'BAJA', name='prioridadticket'), nullable=False),
    sa.Column('estado', sa.Enum('NUEVO', 'ASIGNADO', 'EN_CURSO', 'RECHAZADO', 'DERIVADO', 'FINALIZADO', name='estadoticket'), nullable=False),
    sa.Column('adjuntos', sa.Text(length=1048576), nullable=False),
    sa.Column('referencia', sa.String(length=256), nullable=False),
    sa.Column('solicitante_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('nro_gde', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('observaciones', sa.Text(length=1048576), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['solicitante_id'], ['tickets.usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tickets'
    )
    op.create_table('ticket_area_relation',
    sa.Column('id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('area_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('area_asignada_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_asignada_id'], ['tickets.area.id'], ),
    sa.ForeignKeyConstraint(['area_id'], ['tickets.area.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tickets'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_area_relation', schema='tickets')
    op.drop_table('ticket', schema='tickets')
    op.drop_table('usuario', schema='tickets')
    op.drop_table('area', schema='tickets')
    # ### end Alembic commands ###
