"""Cambios menores en la primera  migracion

Revision ID: 7f1b8a060887
Revises: 06885c5f2787
Create Date: 2023-08-25 21:04:02.092821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f1b8a060887'
down_revision = '06885c5f2787'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'sede_solicitante')
    op.alter_column('usuario', 'email',
                    existing_type=mysql.VARCHAR(length=256),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'email',
                    existing_type=mysql.VARCHAR(length=256),
                    nullable=True)
    op.add_column('ticket', sa.Column('sede_solicitante',
                  mysql.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
